apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-50wb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-50wb@sha256:b6af111f1d248b9091e28fb93a84df46481dd2e3409074adf37e564f51fe9ef6
        name: my-nodejs
        resources: {}
status: {}
